USE qrcode;

-- Drop tables if they exist
DROP TABLE IF EXISTS ABSENCE;
DROP TABLE IF EXISTS ASSOCIATION_6;
DROP TABLE IF EXISTS ETUDIANT;
DROP TABLE IF EXISTS FILIERE;
DROP TABLE IF EXISTS INTEGRER;
DROP TABLE IF EXISTS MODULE;
DROP TABLE IF EXISTS PROFESSEUR;
DROP TABLE IF EXISTS SESSION;
DROP TABLE IF EXISTS SE_PRESENTER;

-- Create tables and foreign keys
CREATE TABLE ABSENCE (
    ID_ABSENCE VARCHAR(100) NOT NULL,
    ID VARCHAR(100) NOT NULL,
    ETAT SMALLINT NULL,
    CONSTRAINT PK_ABSENCE PRIMARY KEY (ID_ABSENCE)
);

CREATE TABLE ASSOCIATION_6 (
    ID VARCHAR(100) NOT NULL,
    ID_MODULE VARCHAR(100) NOT NULL,
    CONSTRAINT PK_ASSOCIATION_6 PRIMARY KEY (ID, ID_MODULE)
);

CREATE TABLE ETUDIANT (
    ID VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NULL,
    MDP VARCHAR(100) NULL,
    ID_FILIERE VARCHAR(100) NOT NULL,
    CONSTRAINT PK_ETUDIANT PRIMARY KEY (ID)
);

CREATE TABLE FILIERE (
    ID_FILIERE VARCHAR(100) NOT NULL,
    NOM_FILIERE CHAR(10) NULL,
    CONSTRAINT PK_FILIERE PRIMARY KEY (ID_FILIERE)
);

CREATE TABLE INTEGRER (
    ID VARCHAR(100) NOT NULL,
    ID_FILIERE VARCHAR(100) NOT NULL,
    CONSTRAINT PK_INTEGRER PRIMARY KEY (ID, ID_FILIERE)
);

CREATE TABLE MODULE (
    ID_MODULE VARCHAR(100) NOT NULL,
    ID VARCHAR(100) NOT NULL,
    NOM_MODULE VARCHAR(100) NULL,
    CONSTRAINT PK_MODULE PRIMARY KEY (ID_MODULE)
);

CREATE TABLE PROFESSEUR (
    ID VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NULL,
    MDP VARCHAR(100) NULL,
    CONSTRAINT PK_PROFESSEUR PRIMARY KEY (ID)
);

CREATE TABLE SESSION (
    ID_SESSION VARCHAR(100) NOT NULL,
    DUREE TIME NULL,
    SALLE VARCHAR(100) NULL,
    CONSTRAINT PK_SESSION PRIMARY KEY (ID_SESSION)
);

CREATE TABLE SE_PRESENTER (
    ID VARCHAR(100) NOT NULL,
    ID_SESSION VARCHAR(100) NOT NULL,
    CONSTRAINT PK_SE_PRESENTER PRIMARY KEY (ID, ID_SESSION)
);

-- Add foreign keys
ALTER TABLE ABSENCE
    ADD CONSTRAINT FK_ABSENCE_AVOIR_ETUDIANT FOREIGN KEY (ID)
    REFERENCES ETUDIANT (ID)
    ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ASSOCIATION_6
    ADD CONSTRAINT FK_ASSOCIAT_ASSOCIATI_ETUDIANT FOREIGN KEY (ID)
    REFERENCES ETUDIANT (ID)
    ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ASSOCIATION_6
    ADD CONSTRAINT FK_ASSOCIAT_ASSOCIATI_MODULE FOREIGN KEY (ID_MODULE)
    REFERENCES MODULE (ID_MODULE)
    ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ETUDIANT
    ADD CONSTRAINT FK_ETUDIANT_JOINDRE_FILIERE FOREIGN KEY (ID_FILIERE)
    REFERENCES FILIERE (ID_FILIERE)
    ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE INTEGRER
    ADD CONSTRAINT FK_INTEGRER_INTEGRER_PROFESSE FOREIGN KEY (ID)
    REFERENCES PROFESSEUR (ID)
    ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE INTEGRER
    ADD CONSTRAINT FK_INTEGRER_INTEGRER2_FILIERE FOREIGN KEY (ID_FILIERE)
    REFERENCES FILIERE (ID_FILIERE)
    ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE MODULE
    ADD CONSTRAINT FK_MODULE_ASSOCIATI_PROFESSE FOREIGN KEY (ID)
    REFERENCES PROFESSEUR (ID)
    ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE SE_PRESENTER
    ADD CONSTRAINT FK_SE_PRESE_SE_PRESEN_SESSION FOREIGN KEY (ID_SESSION)
    REFERENCES SESSION (ID_SESSION)
    ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE SE_PRESENTER
    ADD CONSTRAINT FK_SE_PRESE_SE_PRESEN_ETUDIANT FOREIGN KEY (ID)
    REFERENCES ETUDIANT (ID)
    ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE SE_PRESENTER
    ADD CONSTRAINT FK_SE_PRESE_SE_PRESEN_PROFESSE FOREIGN KEY (ID)
    REFERENCES PROFESSEUR (ID)
    ON UPDATE RESTRICT ON DELETE RESTRICT;
